#!/usr/bin/env node
const ImageTools = require('./images-tools');

const androidSplashImages = [ null
    , {width:  800, height:  480,  file: 'launch/android/drawable-land-hdpi/screen.png' }
    , {width:  480, height:  320,  file: 'launch/android/drawable-land-mdpi/screen.png' }
    , {width: 1280, height:  720,  file: 'launch/android/drawable-land-xhdpi/screen.png' }
    , {width: 1600, height:  960,  file: 'launch/android/drawable-land-xxhdpi/screen.png' }
    , {width: 1920, height: 1280,  file: 'launch/android/drawable-land-xxxhdpi/screen.png' }
    , {width:  480, height:  800,  file: 'launch/android/drawable-hdpi/screen.png' }
    , {width:  320, height:  480,  file: 'launch/android/drawable-mdpi/screen.png' }
    , {width:  720, height: 1280,  file: 'launch/android/drawable-xhdpi/screen.png' }
    , {width:  960, height: 1600,  file: 'launch/android/drawable-xxhdpi/screen.png' }
    , {width: 1280, height: 1920,  file: 'launch/android/drawable-xxxhdpi/screen.png' }
];

const androidIconImages = [ null
    , {width:   72, height:   72,  file: 'icons/android/mipmap-hdpi/ic_launcher.png' }
    , {width:   48, height:   48,  file: 'icons/android/mipmap-mdpi/ic_launcher.png' }
    , {width:   96, height:   96,  file: 'icons/android/mipmap-xhdpi/ic_launcher.png' }
    , {width:  144, height:  144,  file: 'icons/android/mipmap-xxhdpi/ic_launcher.png' }
    , {width:  192, height:  192,  file: 'icons/android/mipmap-xxxhdpi/ic_launcher.png' }
];

const iOSSplashImages = [ null
    , { width:  640, height: 1136, file: 'launch/ios/640x1136.png' }
    , { width:  750, height: 1334, file: 'launch/ios/750x1334.png' }
    , { width: 1125, height: 2436, file: 'launch/ios/1125x2436.png' }
    , { width: 2208, height: 1242, file: 'launch/ios/2208x1242.png' }
    , { width: 1242, height: 2208, file: 'launch/ios/1242x2208.png' }
    , { width: 2436, height: 1125, file: 'launch/ios/2436x1125.png' }
    , { width: 1024, height:  768, file: 'launch/ios/1024x768.png' }
    , { width: 1536, height: 2048, file: 'launch/ios/1536x2048.png' }
    , { width: 2048, height: 1536, file: 'launch/ios/2048x1536.png' }
    , { width:  768, height: 1024, file: 'launch/ios/768x1024.png' }
    , { width:  320, height:  480, file: 'launch/ios/320x480.png' }
    , { width:  640, height:  960, file: 'launch/ios/640x960.png' }
];

const iOSIconImages = [ null
    , { width:   20, height:   20, file: 'icons/ios/20.png' }
    , { width:   29, height:   29, file: 'icons/ios/29.png' }
    , { width:   40, height:   40, file: 'icons/ios/40.png' }
    , { width:   50, height:   50, file: 'icons/ios/50.png' }
    , { width:   57, height:   57, file: 'icons/ios/57.png' }
    , { width:   58, height:   58, file: 'icons/ios/58.png' }
    , { width:   60, height:   60, file: 'icons/ios/60.png' }
    , { width:   72, height:   72, file: 'icons/ios/72.png' }
    , { width:   76, height:   76, file: 'icons/ios/76.png' }
    , { width:   80, height:   80, file: 'icons/ios/80.png' }
    , { width:   87, height:   87, file: 'icons/ios/87.png' }
    , { width:  100, height:  100, file: 'icons/ios/100.png' }
    , { width:  114, height:  114, file: 'icons/ios/114.png' }
    , { width:  120, height:  120, file: 'icons/ios/120.png' }
    , { width:  144, height:  144, file: 'icons/ios/144.png' }
    , { width:  152, height:  152, file: 'icons/ios/152.png' }
    , { width:  167, height:  167, file: 'icons/ios/167.png' }
    , { width:  180, height:  180, file: 'icons/ios/180.png' }
    , { width: 1024, height: 1024, file: 'icons/ios/1024.png' }

];


async function run() {
    let tools = new ImageTools();
    await tools.execute(androidIconImages, './icon.png','Android icons');
    await tools.execute(androidSplashImages, './splash.png','Android splash');
    await tools.execute(iOSIconImages, './icon.png','iOS icons');
    await tools.execute(iOSSplashImages, './splash.png','iOS splash');
}


run().finally(() => {
    console.log('\n\nprocess finished');
});