#!/usr/bin/env node

const ImageTools = require('./images-tools');
const path = process.argv[2];
if (!path) {
    console.error('missing build absolute path argument');
    process.exit(1);
}
console.log('\n\nGenerating images for build ' + path);

const androidSplashImages = [ null
    , {width:  800, height:  480,  file: path + '/android/project/app/src/main/res/drawable-land-hdpi/screen.png' }
    , {width:  320, height:  200,  file: path + '/android/project/app/src/main/res/drawable-land-ldpi/screen.png' }
    , {width:  480, height:  320,  file: path + '/android/project/app/src/main/res/drawable-land-mdpi/screen.png' }
    , {width: 1280, height:  720,  file: path + '/android/project/app/src/main/res/drawable-land-xhdpi/screen.png' }
    , {width: 1600, height:  960,  file: path + '/android/project/app/src/main/res/drawable-land-xxhdpi/screen.png' }
    , {width: 1920, height: 1280,  file: path + '/android/project/app/src/main/res/drawable-land-xxxhdpi/screen.png' }
    , {width:  480, height:  800,  file: path + '/android/project/app/src/main/res/drawable-port-hdpi/screen.png' }
    , {width:  200, height:  320,  file: path + '/android/project/app/src/main/res/drawable-port-ldpi/screen.png' }
    , {width:  320, height:  480,  file: path + '/android/project/app/src/main/res/drawable-port-mdpi/screen.png' }
    , {width:  720, height: 1280,  file: path + '/android/project/app/src/main/res/drawable-port-xhdpi/screen.png' }
    , {width:  960, height: 1600,  file: path + '/android/project/app/src/main/res/drawable-port-xxhdpi/screen.png' }
    , {width: 1280, height: 1920,  file: path + '/android/project/app/src/main/res/drawable-port-xxxhdpi/screen.png' }
];

const iOSIcons = [ null
    , {width:  48, height:  48,  file: path + '/ios/project/Utter Coach/Images.xcassets/AppIcon.appiconset/icon-24@2x.png' }
    , {width:  55, height:  55,  file: path + '/ios/project/Utter Coach/Images.xcassets/AppIcon.appiconset/icon-27.5@2x.png' }
    , {width:  88, height:  88,  file: path + '/ios/project/Utter Coach/Images.xcassets/AppIcon.appiconset/icon-44@2x.png' }
    , {width: 172, height: 172,  file: path + '/ios/project/Utter Coach/Images.xcassets/AppIcon.appiconset/icon-86@2x.png' }
    , {width: 196, height: 196,  file: path + '/ios/project/Utter Coach/Images.xcassets/AppIcon.appiconset/icon-98@2x.png' }
    , {width: 216, height: 216,  file: path + '/ios/project/Utter Coach/Images.xcassets/AppIcon.appiconset/216.png' }
];

const iOSSplash = [ null
    , {width:  768, height:  1004,  file: path + '/ios/project/Utter Coach/Images.xcassets/LaunchImage.launchimage/768x1004.png' }
    , {width: 1536, height:  2008,  file: path + '/ios/project/Utter Coach/Images.xcassets/LaunchImage.launchimage/1536x2008.png' }
    , {width: 1024, height:   748,  file: path + '/ios/project/Utter Coach/Images.xcassets/LaunchImage.launchimage/1024x748.png' }
    , {width: 2048, height:  1496,  file: path + '/ios/project/Utter Coach/Images.xcassets/LaunchImage.launchimage/2048x1496.png' }
]

async function run() {
    let tools = new ImageTools();
    await tools.execute(androidSplashImages, './splash.png','Android splash');
    await tools.execute(iOSIcons, './icon.png','iOS icons');
    await tools.execute(iOSSplash, './splash.png','iOS splash');

}


run().finally(() => {
    console.log('\n\nprocess finished');
});
